//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Model;
   
    
    public partial class HOTELESEntities : DbContext
    {
        public HOTELESEntities()
            : base("name=HOTELESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Model.HABITACION_SEDE> HabitacionSedes { get; set; }
        public virtual DbSet<RESERVAS> Reservas { get; set; }
        public virtual DbSet<SEDES> Sede { get; set; }
        public virtual DbSet<TARIFAS> Terifas { get; set; }
        public virtual DbSet<TIPO_HABITACIONES> Tipo_Habitaciones { get; set; }
    }
}
