CREATE DATABASE HOTELES;
GO

CREATE TABLE SEDES(
ID_SEDE INT IDENTITY(1,1) NOT NULL,
NOMBRE_SEDE VARCHAR(50) NOT NULL,
CUPO_MAX INT NOT NULL
CONSTRAINT PK_SEDES PRIMARY KEY CLUSTERED (ID_SEDE ASC)
);
GO

CREATE TABLE TIPO_HABITACIONES(
ID_TIPO_HABITACION INT IDENTITY(1,1) NOT NULL,
NOMBRE_TIPO VARCHAR(50) NOT NULL
CONSTRAINT PK_TIPO_HABITACIONES PRIMARY KEY CLUSTERED (ID_TIPO_HABITACION ASC)
);
GO

CREATE TABLE HABITACION_SEDE(
ID_HABITACION_SEDE INT IDENTITY(1,1) NOT NULL,
ID_SEDE INT NOT NULL,
ID_TIPO_HABITACION INT NOT NULL,
NRO_HABITACIONES INT NOT NULL
CONSTRAINT PK_HABITACION_SEDE PRIMARY KEY CLUSTERED (ID_HABITACION_SEDE ASC)
);
GO

CREATE TABLE RESERVAS(
ID_RESERVA INT IDENTITY(1,1) NOT NULL,
ID_SEDE INT NOT NULL,
ID_TIPO_HABITACION INT NOT NULL,
FECHA_IN DATETIME NOT NULL,
FECHA_OUT DATETIME NOT NULL,
NRO_PERSONAS INT NOT NULL
CONSTRAINT PK_RESERVAS PRIMARY KEY CLUSTERED (ID_RESERVA ASC)
);
GO

CREATE TABLE TARIFAS(
ID_TARIFA INT IDENTITY(1,1) NOT NULL,
ID_SEDE INT NOT NULL,
ID_TIPO_HABITACION INT NOT NULL,
FECHA_INI DATETIME NOT NULL,
FECHA_FIN DATETIME NOT NULL,
VALOR_NOCHE_PERSONA DECIMAL(10,2)
CONSTRAINT PK_TARIFAS PRIMARY KEY CLUSTERED (ID_TARIFA ASC)
);
GO

ALTER TABLE HABITACION_SEDE  WITH CHECK ADD  CONSTRAINT FK_HABITACION_SEDE_SEDES FOREIGN KEY(ID_SEDE)
REFERENCES SEDES (ID_SEDE);
GO

ALTER TABLE HABITACION_SEDE  WITH CHECK ADD  CONSTRAINT FK_HABITACION_SEDE_TIPO_HABITACIONES FOREIGN KEY(ID_TIPO_HABITACION)
REFERENCES TIPO_HABITACIONES (ID_TIPO_HABITACION);
GO

ALTER TABLE RESERVAS  WITH CHECK ADD  CONSTRAINT FK_RESERVAS_SEDES FOREIGN KEY(ID_SEDE)
REFERENCES SEDES (ID_SEDE);
GO

ALTER TABLE RESERVAS  WITH CHECK ADD  CONSTRAINT FK_RESERVAS_TIPO_HABITACIONES FOREIGN KEY(ID_TIPO_HABITACION)
REFERENCES TIPO_HABITACIONES (ID_TIPO_HABITACION);
GO

ALTER TABLE TARIFAS  WITH CHECK ADD  CONSTRAINT FK_TARIFAS_SEDES FOREIGN KEY(ID_SEDE)
REFERENCES SEDES (ID_SEDE);
GO

ALTER TABLE TARIFAS  WITH CHECK ADD  CONSTRAINT FK_TARIFAS_TIPO_HABITACIONES FOREIGN KEY(ID_TIPO_HABITACION)
REFERENCES TIPO_HABITACIONES (ID_TIPO_HABITACION);
GO



